import {healthOverviewMarkup,healthSummary} from './health.js';
/* today screen composition; calculations and persistence stay in domain modules. */
export function createTodayScreen(ui){
  const {enter,heading,readinessMarkup,saveStatus,bindSaveStatus,route,checkin,sheet}=ui;

function today(){
    enter('home-overview','home');const resume=AWJ_TRAINING_SESSION.isResumableWorkout(state,sessions),plan=window.AWJ_ENHANCEMENTS_UI.adaptiveTodayPlan(),id=resume?state.session:plan.targetSession,s=sessions[id]||{name:"Recovery day",meta:"No scheduled workout",description:plan.detail,exercises:[]},ls=sessionText(id,s),duration=id?(s.duration||ls.meta.match(/\d+[–-]\d+ min|\d+ min/)?.[0]||''):'';
    const sessionDetail=id?[duration||null,`${s.exercises.length} exercises`,resume?`Exercise ${state.index+1}`:null].filter(Boolean).map(esc).join(' · '):'A lighter day for rest, gentle movement, and your daily practices.';
    const data=healthSummary(),totals=foodTotals(),profile=foodProfile(),water=Number(state.water?.[isoDay()]||0);
    app.innerHTML=AWJ_SAFE_DOM.sanitize(`${heading('Today',new Date().toLocaleDateString(state.preferences?.language==='ar'?'ar-EG':'en-GB',{weekday:'long',day:'numeric',month:'long'}))}${healthOverviewMarkup(data)}${readinessMarkup()}<div class="today-dashboard"><section class="today-session ${resume?'is-resuming':''}" data-today-session><div><span class="eyebrow">${resume?'In progress':id?"Today's workout":"Today’s focus"}</span><h2>${esc(ls.name)}</h2><p>${sessionDetail}</p></div><button class="primary-action" data-today-start>${resume?'Resume workout':id?'Start workout':'Review recovery'}</button><button class="quiet-action" data-today-preview>${id?'Review exercises':'View routines'}</button></section><div class="today-support"><nav class="daily-overview" aria-label="Daily overview"><a href="#/nutrition/today"><span>Nutrition logged</span><strong>${Math.round(totals.calories||0)} <small>/ ${profile.calories} kcal</small></strong><progress max="${profile.calories||1}" value="${Math.min(profile.calories,totals.calories||0)}" aria-label="Calories logged"></progress></a><a href="#/nutrition/today"><span>Water logged</span><strong>${esc(window.waterDisplay(water))} <small>/ ${esc(window.waterDisplay(profile.water))}</small></strong><progress max="${profile.water||1}" value="${Math.min(profile.water,water)}" aria-label="Water logged"></progress></a></nav><nav class="quick-actions" aria-label="Quick actions"><button data-adjust-today>Adjust today</button><button data-today-activity>Log activity</button><button data-today-food>Meal / water</button><button data-today-checkin>Check-in</button></nav></div></div><section data-daily-routines></section>${saveStatus()}`);
    document.querySelector('[data-today-start]').onclick=()=>{if(!id){route("health-vitals");return;}if(!resume)AWJ_ADAPTIVE_COACH.applyPlan(state,plan,sessions);startSession(id);};
    document.querySelector('[data-today-preview]').onclick=()=>id?showSessionPreview(id):route('training-program');
    document.querySelector('[data-adjust-today]').onclick=()=>sheet('Adjust today',`<p>Choose a lighter option using your existing plan.</p><button class="primary-action" data-adjust-light>Short workout</button><button data-adjust-schedule>Move this workout</button>`,(root,close)=>{root.querySelector('[data-adjust-light]').onclick=()=>{close();renderBadDay();};root.querySelector('[data-adjust-schedule]').onclick=()=>{close();route('settings-schedule');};});
    document.querySelector('[data-today-activity]').onclick=()=>showLogActivity();document.querySelector('[data-today-food]').onclick=()=>route('nutrition-log');document.querySelector('[data-today-checkin]').onclick=checkin;
    window.AWJ_HABITS.mount();bindSaveStatus();
  }
  return {today};
}
