window.REP_FEATURES=(function(){
  const encoder=new TextEncoder(),decoder=new TextDecoder();
  const DB_NAME="rep-device-vault-v1",STORE="vault";
  const b64=bytes=>{let text="";for(const byte of bytes)text+=String.fromCharCode(byte);return btoa(text);};
  const unb64=text=>{const raw=atob(String(text||"")),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes;};
  function openVault(){return new Promise((resolve,reject)=>{if(!indexedDB)return reject(Error("Device backup is unavailable."));const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function vaultGet(key){const db=await openVault();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),request=tx.objectStore(STORE).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();});}
  async function vaultPut(key,value){const db=await openVault();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,key);tx.oncomplete=()=>{db.close();resolve(value);};tx.onerror=()=>{db.close();reject(tx.error);};});}
  async function vaultDelete(key){const db=await openVault();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(key);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};});}
  async function vaultEntries(prefix){const db=await openVault();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),request=tx.objectStore(STORE).openCursor(),rows=[];request.onsuccess=()=>{const cursor=request.result;if(!cursor){db.close();resolve(rows);return;}if(String(cursor.key).startsWith(prefix))rows.push([cursor.key,cursor.value]);cursor.continue();};request.onerror=()=>{db.close();reject(request.error);};});}
  async function deviceKey(){let key=await vaultGet("device-key");if(key)return key;key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);await vaultPut("device-key",key);return key;}
  async function createDeviceSnapshot(data){const key=await deviceKey(),iv=crypto.getRandomValues(new Uint8Array(12)),plain=encoder.encode(JSON.stringify(data)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,plain),record={version:1,createdAt:new Date().toISOString(),iv:b64(iv),ciphertext:b64(new Uint8Array(cipher))},history=await vaultGet("snapshots")||[];history.unshift(record);await vaultPut("snapshots",history.slice(0,5));await vaultPut("latest",record);return record;}
  async function restoreDeviceSnapshot(index=0){const history=await vaultGet("snapshots")||[],record=history[index]||await vaultGet("latest");if(!record)throw Error("No automatic device backup is available yet.");const key=await deviceKey(),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(record.iv)},key,unb64(record.ciphertext));return {data:JSON.parse(decoder.decode(plain)),createdAt:record.createdAt};}
  async function backupHistory(){try{const history=await vaultGet("snapshots")||[],latest=await vaultGet("latest");return (history.length?history:(latest?[latest]:[])).map(record=>record.createdAt);}catch{return [];}}
  async function backupStatus(){return (await backupHistory())[0]||null;}
  let snapshotTimer=null,lastSnapshotAt=Number(localStorage.getItem("rep-last-device-snapshot-at")||0);
  function scheduleSnapshot(data){
    const minimumInterval=6*60*60*1000;
    if(Date.now()-lastSnapshotAt<minimumInterval)return;
    clearTimeout(snapshotTimer);
    const run=()=>createDeviceSnapshot(data).then(()=>{lastSnapshotAt=Date.now();localStorage.setItem("rep-last-device-snapshot-at",String(lastSnapshotAt));}).catch(()=>{});
    snapshotTimer=setTimeout(()=>{if("requestIdleCallback" in window)requestIdleCallback(run,{timeout:3000});else run();},1500);
  }
  async function passphraseKey(passphrase,salt,usage){const material=await crypto.subtle.importKey("raw",encoder.encode(passphrase),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,usage);}
  const backupHeader=createdAt=>({app:"Rep Gym Companion",schema:5,encrypted:true,cipher:"AES-256-GCM",kdf:"PBKDF2-SHA256",iterations:250000,format:"rep-health-export/v5",createdAt});
  async function encryptExport(data,passphrase){if(String(passphrase).length<8)throw Error("Use a passphrase with at least 8 characters.");const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await passphraseKey(passphrase,salt,["encrypt"]),plain=encoder.encode(JSON.stringify(data)),header=backupHeader(new Date().toISOString()),additionalData=encoder.encode(JSON.stringify(header)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv,additionalData},key,plain);return {...header,salt:b64(salt),iv:b64(iv),ciphertext:b64(new Uint8Array(cipher))};}
  async function decryptExport(payload,passphrase){if(!payload?.encrypted||![4,5].includes(payload?.schema))throw Error("This is not a supported encrypted Rep backup.");if(payload.schema===5&&(payload.app!=="Rep Gym Companion"||payload.cipher!=="AES-256-GCM"||payload.kdf!=="PBKDF2-SHA256"||payload.iterations!==250000||payload.format!=="rep-health-export/v5"||!payload.createdAt))throw Error("The encrypted backup header is invalid.");const key=await passphraseKey(passphrase,unb64(payload.salt),["decrypt"]);try{const algorithm={name:"AES-GCM",iv:unb64(payload.iv)};if(payload.schema===5)algorithm.additionalData=encoder.encode(JSON.stringify(backupHeader(payload.createdAt)));const plain=await crypto.subtle.decrypt(algorithm,key,unb64(payload.ciphertext));return JSON.parse(decoder.decode(plain));}catch{throw Error("The passphrase is incorrect or the backup is damaged.");}}
  function downloadJson(payload,filename){const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200);}
  async function saveProgressPhoto(input){
    const bytes=input?.bytes instanceof Uint8Array?input.bytes:new Uint8Array(input?.bytes||[]);if(!bytes.length||bytes.length>3_000_000)throw Error("Use a photo smaller than 3 MB after processing.");
    const id=String(input.id||`photo-${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`).slice(0,100),key=await deviceKey(),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,bytes),record={version:1,id,date:String(input.date||localDay(new Date())).slice(0,10),label:String(input.label||"Progress photo").trim().slice(0,80),mime:["image/jpeg","image/png","image/webp"].includes(input.mime)?input.mime:"image/jpeg",createdAt:new Date().toISOString(),iv:b64(iv),ciphertext:b64(new Uint8Array(cipher))};
    await vaultPut(`progress-photo:${id}`,record);return {id:record.id,date:record.date,label:record.label,mime:record.mime,createdAt:record.createdAt};
  }
  async function decryptProgressRecord(record){const key=await deviceKey(),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(record.iv)},key,unb64(record.ciphertext));return {...record,bytes:new Uint8Array(plain)};}
  async function listProgressPhotos({includeBytes=false}={}){const rows=await vaultEntries("progress-photo:"),results=[];for(const [,record] of rows){const item={id:record.id,date:record.date,label:record.label,mime:record.mime,createdAt:record.createdAt};if(includeBytes){const decrypted=await decryptProgressRecord(record);item.bytes=decrypted.bytes;}results.push(item);}return results.sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));}
  async function deleteProgressPhoto(id){await vaultDelete(`progress-photo:${String(id).slice(0,100)}`);}
  async function exportProgressPhotos(){return (await listProgressPhotos({includeBytes:true})).map(item=>({...item,bytes:b64(item.bytes)}));}
  async function importProgressPhotos(items){for(const item of Array.isArray(items)?items.slice(0,80):[]){const bytes=unb64(item.bytes);await saveProgressPhoto({...item,bytes});}}
  function localDay(date){return [date.getFullYear(),String(date.getMonth()+1).padStart(2,"0"),String(date.getDate()).padStart(2,"0")].join("-");}
  function dayKeys(count=7){const days=[];for(let i=count-1;i>=0;i--){const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-i);days.push(localDay(date));}return days;}
  return {createDeviceSnapshot,restoreDeviceSnapshot,backupStatus,backupHistory,scheduleSnapshot,encryptExport,decryptExport,downloadJson,dayKeys,saveProgressPhoto,listProgressPhotos,deleteProgressPhoto,exportProgressPhotos,importProgressPhotos};
})();
